Работа со строкой запроса
htmlacademy-php1/230166-readme-14 pull request #10
Opened 2022-04-22 12:19 UTC by LoremLipsum

2022-04-23 03:51 UTC, b1rdex requested changes

2022-04-23 03:51 UTC, b1rdex commented on config/queries.php
> +}
Желательно, чтобы эта функция сразу же и выводила результат `include_template('error.php'` на страницу, а не возвращала $page_content куда-то, т.к. там переменную скорее всего просто перезапишет другая функция.

2022-04-23 03:51 UTC, b1rdex commented on index.php
> +    'link' => $link
В шаблон не стоит передавать подключение к бд, надо что-то с этим придумать. Например, внутри get_popular_posts сразу запрашивать целиком данные для постов.

2022-04-23 03:51 UTC, b1rdex commented on templates/popular.php
> +                        'link' => $link
Продублирую, чтобы не пропустить потом: подключение к бд не должно быть в шаблонах

2022-04-23 03:51 UTC, b1rdex commented on templates/post-link.php
> +          <h3><?=$title;?></h3>
xss

2022-04-23 03:51 UTC, b1rdex commented on templates/post-link.php
> +          <img src="https://www.google.com/s2/favicons?domain=<?=$url;?>" alt="Иконка">
xss

2022-04-23 03:51 UTC, b1rdex commented on templates/post-photo.php
> +	<img src="img/<?=$img_url;?>" alt="Фото от пользователя" width="760" height="507">
xss

2022-04-23 03:51 UTC, b1rdex commented on templates/post-quote.php
> +      <cite><?=$author;?></cite>
xss

2022-04-23 03:51 UTC, b1rdex commented on templates/post-text.php
> +      <?=$text;?>
xss

2022-04-23 03:51 UTC, b1rdex commented on templates/post_details.php
> +                                'text' => esc($post['text'])
А, вот оно что. Выше всё про xss зря получается написал)) но, честно говоря, лучше делать esc() внутри `post-*.php`

2022-04-25 05:33 UTC, b1rdex requested changes

2022-04-25 05:33 UTC, b1rdex commented on config/init.php
> +    die();
```suggestion
    show_error($error);
```

2022-04-25 05:33 UTC, b1rdex commented on config/sql_functions.php
> +}
```suggestion
*/
function show_error($error): void {
    $page_content = include_template('error.php', ['error' => $error]);
    die($page_content);
}
```

2022-04-25 05:33 UTC, b1rdex commented on config/sql_functions.php
> +    show_error($page_content, mysqli_error($link));
```suggestion
    show_error(mysqli_error($link));
```

2022-04-25 05:33 UTC, b1rdex commented on config/sql_functions.php
> +            WHERE type_id = $type_id
sql injection. Нужно либо явно приводить к типу int, либо использовать подстановку параметров в sql запрос

2022-04-25 05:33 UTC, b1rdex commented on config/sql_functions.php
> +    show_error($page_content, mysqli_error($link));
```suggestion
    show_error(mysqli_error($link));
```

2022-04-25 05:33 UTC, b1rdex commented on config/sql_functions.php
> +    show_error($page_content, mysqli_error($link));
```suggestion
    show_error(mysqli_error($link));
```

2022-04-25 05:33 UTC, b1rdex commented on config/sql_functions.php
> +            WHERE p.id = $post_id";
sql injection

2022-04-25 05:33 UTC, b1rdex commented on config/sql_functions.php
> +            WHERE c.post_id = $post_id";
sql injection

2022-04-25 05:33 UTC, b1rdex commented on config/sql_functions.php
> +    show_error($page_content, mysqli_error($link));
```suggestion
    show_error(mysqli_error($link));
```

2022-04-25 05:33 UTC, b1rdex commented on config/sql_functions.php
> +            WHERE ph.post_id = $post_id
sql injection

2022-04-25 05:33 UTC, b1rdex commented on config/sql_functions.php
> +    show_error($page_content, mysqli_error($link));
```suggestion
    show_error(mysqli_error($link));
```

2022-04-25 05:33 UTC, b1rdex commented on config/sql_functions.php
> +    $sql = "SELECT COUNT(id) AS count FROM fav WHERE post_id = $post_id";
sql injection

2022-04-25 05:33 UTC, b1rdex commented on config/sql_functions.php
> +    show_error($page_content, mysqli_error($link));
```suggestion
    show_error(mysqli_error($link));
```

2022-04-25 05:33 UTC, b1rdex commented on config/sql_functions.php
> +    $sql = "SELECT COUNT(id) AS count FROM comment WHERE post_id = $post_id";
sql injection

2022-04-25 05:33 UTC, b1rdex commented on config/sql_functions.php
> +    show_error($page_content, mysqli_error($link));
```suggestion
    show_error(mysqli_error($link));
```

2022-04-25 05:33 UTC, b1rdex commented on config/sql_functions.php
> +    $sql = "SELECT COUNT(id) AS count FROM post WHERE user_id = $user_id";
sql injection

2022-04-25 05:33 UTC, b1rdex commented on config/sql_functions.php
> +    show_error($page_content, mysqli_error($link));
```suggestion
    show_error(mysqli_error($link));
```

2022-04-25 05:33 UTC, b1rdex commented on config/sql_functions.php
> +    $sql = "SELECT COUNT(id) AS count FROM subscribe WHERE user_id_publisher = $user_id";
sql injection

2022-04-25 05:33 UTC, b1rdex commented on config/sql_functions.php
> +    show_error($page_content, mysqli_error($link));
```suggestion
    show_error(mysqli_error($link));
```

2022-04-25 05:33 UTC, b1rdex commented on templates/post_details.php
> +    $is_show_comments = filter_input(INPUT_GET, 'is_show_comments');
желательно это вынести в post.php и передавать сюда значение переменной

2022-04-25 14:58 UTC, LoremLipsum commented on config/sql_functions.php
> +    show_error($page_content, mysqli_error($link));
Да необязательно каждую строчку править, можно написать и тд.

2022-04-25 15:36 UTC, LoremLipsum commented on config/sql_functions.php
> +    $sql = "SELECT COUNT(id) AS count FROM subscribe WHERE user_id_publisher = $user_id";
![image](https://user-images.githubusercontent.com/27227939/165123031-0925db54-db15-429d-bc25-7bf7fe3fa463.png)
А здесь я неправильно написала? Я проде привела к к типу int
https://www.php.net/manual/ru/language.types.type-juggling.php

2022-04-25 15:57 UTC, LoremLipsum commented on config/sql_functions.php
> +            WHERE type_id = $type_id
Как использовать подстановку? Чет не доходит

2022-05-23 10:33 UTC, merged